---
- name: Restart Motioneye
  hosts: all
  become: true
  tasks:
    - name: Restart service motioneye, in all cases
      ansible.builtin.service:
        name: motioneye
        state: restarted
        sleep: 5
