---
- hosts: NXFilter

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day
